config/routes.rb
Rails.application.routes.draw do

 resources :chars
get "createchart" => "chars#createchart"
root 'chars#index'

end

app/models/char.rb
class Char < ActiveRecord::Base
end

app/models/percen.rb
class Percen < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/chars_controller.rb
class CharsController < ApplicationController
  def index
@chars = Char.all
  end

def destroy
  @char = Char.find(params[:id])
  @char.destroy
 
redirect_to(:action => :index)
end

 def show
    @char = Char.find(params[:id])
@text=@char['title']
@percent= Percen.where(chartid: params[:id])


@data=[]
@categories=[]
@per=[]
 @percent.each do |item|
#@data.unshift("{name: '"+item.name+"', y:"+item.per.to_s+"}")
@data.unshift "{name: '"+item.name+"', y:"+item.per.to_s+"}"

@per.unshift(item.per)
@categories.unshift(item.name)
end
@data=@data.to_s.tr('"','')


  end

def createchart
 @id=params[:"id"] 
    @char = Char.find(@id)
@number =@char.number
while( @number > 0 )
percen = Percen.new
percen.chartid = @id
@num=@number.to_s
name="name"+@num
value="value"+@num
percen.name = params[name] 
percen.per = params[value]  




percen.save

  @number -= 1

end

@percent= Percen.where(chartid: @id)
  redirect_to @char
  end

 def new
@char = Char.new
  end
 
  def create
 @char = Char.new(params.require(:char).permit(:title, :number))
 
  @char.save
  redirect_to @char
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chart_helper.rb
module ChartHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/chars/createchart.html.erb
<%= @id %>
<%= @name %>

app/views/chars/index.html.erb
<!DOCTYPE HTML>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
        <title>Highcharts Example</title>

        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script src="http://code.highcharts.com/highcharts.js"></script>

      
    </head>
    <body bgcolor="#E6E6FA">

<br>
<% if (@chars) %>
<center>

<h2>All charts</h2>

</center>

<table>
  <tr>
    <th>Chart </th>
    <th>action</th>
  </tr>
 
  <% @chars.each do |char| %>
    <tr>
      <td><%= char.title %></td>
      <td><a href="/chars/<%= char.id %>"> show </a>
</td>
<td><%= link_to 'Destroy', char_path(char),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

<% end %>
<br>


Want to add new chart ? 

<%= form_for :char, url: chars_path do |f| %>
    <%= f.label :title %><br>
    <%= f.text_field :title , :required => true%>
  </p>
 
  <p>
    <%= f.label :"number of entities" %><br>
    <%= f.text_field :number , :required => true, :pattern => '[0-9]*' %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>


    </body>
</html>

app/views/chars/show.html.erb
<html>

<head>
    <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.8.2/jquery.min.js"></script>
<script src="https://code.highcharts.com/highcharts.js"></script>

        <style type="text/css">
${demo.css}
        </style>
       

</head>
<body bgcolor="#E6E6FA">
<a href="/" > All charts </a>
<form>
<input id="f" type="hidden" value='<%= @data %>' >
<input id="text" type="hidden" value='<%= @text %>' >
<input id="cat" type="hidden" value='<%= @categories %>' >
<input id="per" type="hidden" value='<%= @per %>' >
</form>

<p>
  <strong>Title:</strong>
  <%= @char.title %>
</p>

<p>
  <strong>Number of entities:</strong>
  <%= @char.number %>
</p>

<% if (@percent[0].nil?) %>
<form accept-charset="UTF-8" action="/createchart" method="get">
  <input id="q" name="id" type="hidden" value="<%= @char.id %>" />

<% while( @char.number > 0 ) %>
  <label for="q">name :</label>
  <input  name="name<%= @char.number %>" type="text" />

<label for="q">value :</label>
  <input  name="value<%= @char.number %>" type="text" />
<br>



<% @char.number-= 1 %>
   <% end %>
  <input name="commit" type="submit" value="create chart" />
</form>
<% else %>

<select id = "mySelect" onchange="myFunction()">
  <option value="pie"  >Pie chart</option>
  <option value="line" >Line chart</option>
</select>

<div id="container" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto"></div>
<div id="c" style="min-width: 310px; height: 400px; margin: 0 auto ; display:none"></div>
   <% end %>




<% @percent.each do |item|%>
Percentage : <%= item.per %>
Name : <%= item.name %>
<br>
    <% end %>


 <script type="text/javascript">
 if(!window.location.hash) {
        window.location = window.location + '#loaded';
        window.location.reload();
    }
var test = 0; 
function myFunction()

{

if(test==0)
test=1;
else 
test=0;

if(test == 0)
{
document.getElementById("container").style.display = 'block';

    document.getElementById("c").style.display = 'none';

}


if(test == 1)
{
document.getElementById("c").style.display = 'block';
    document.getElementById("container").style.display = 'none';

}

}


$(function () {

    $(document).ready(function () {
d = document.getElementById("f").value;
d= String(d);
text=document.getElementById("text").value;
cat=document.getElementById("cat").value;
per=document.getElementById("per").value;

var jsonObj = eval(d);



        // Build the chart
        $('#container').highcharts({
            chart: {
                plotBackgroundColor: null,
                plotBorderWidth: null,
                plotShadow: false,
                type: 'pie'
            },
            title: {
                text: text
            },
            tooltip: {
                pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
            },
            plotOptions: {
                pie: {
                    allowPointSelect: true,
                    cursor: 'pointer',
                    dataLabels: {
                        enabled: false
                    },
                    showInLegend: true
                }
            },
            series: [{ 
                name: "Brands",
                colorByPoint: true,
                data:  jsonObj
            }]
        });
    });
});




cat= cat.value;
cat=eval(cat);
per=per.value;
per=eval(per);


$(function () {
    $('#c').highcharts({
        title: {
            text: "<%= @char.title %>",
            x: -20 //center
        },
        subtitle: {
            text: '',
            x: -20
        },
        xAxis: {
            categories: cat
        },
        yAxis: {
            title: {
                text: ''
            },
            plotLines: [{
                value: 0,
                width: 1,
                color: '#808080'
            }]
        },
        tooltip: {
            valueSuffix: ''
        },
        legend: {
            layout: 'vertical',
            align: 'right',
            verticalAlign: 'middle',
            borderWidth: 0
        },
        series: [{
            name: "<%= @char.title %>",
            data: per
        }, ]
    });
});
        </script>






</body>

</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Task</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>